<a href="https://colab.research.google.com/github/mjjaiavinash/avinash-codebooster-2026/blob/main/Day_1_workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/student_performance.csv')

In [ ]:
df.head(10)

   student_id          name  age  gender        department  semester  \
0        1001  Aarav Sharma   19    Male  Computer Science         2
1        1002   Priya Patel   20  Female  Computer Science         2
2        1003   Rohit Verma   19    Male       Electronics         2
3        1004   Sneha Reddy   20  Female        Mechanical         2
4        1005    Arjun Nair   19    Male  Computer Science         2
5        1006   Meera Joshi   20  Female       Electronics         2
6        1007   Kiran Kumar   21    Male             Civil         2
7        1008   Divya Singh   19  Female  Computer Science         2
8        1009  Rahul Mishra   20    Male        Mechanical         2
9        1010    Ananya Das   19  Female  Computer Science         2

   math_score  science_score  english_score  programming_score  \
0          85             78             72                 91
1          76             82             88                 79
2          65             74             61                 55
3          70             80             75                 48
4          92             88             81                 95
5          58             66             70                 52
6          73             69             65                 40
7          88             91             84                 93
8          62             71             58                 45
9          95             89             90                 97

   attendance_percentage       city  admission_year
0                     92     Mumbai            2023
1                     87  Ahmedabad            2023
2                     78      Delhi            2023
3                     95  Hyderabad            2023
4                     90      Kochi            2023
5                     72       Pune            2023
6                     85  Bangalore            2023
7                     96    Lucknow            2023
8                     68   Varanasi            2023
9                     98    Kolkata            2023

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
df.shape

(30, 13)

In [ ]:
df.columns.to_list()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [ ]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
df['math_score']

0     85
1     76
2     65
3     70
4     92
5     58
6     73
7     88
8     62
9     95
10    80
11    67
12    83
13    74
14    71
15    87
16    56
17    90
18    68
19    79
20    64
21    93
22    61
23    77
24    86
25    72
26    84
27    60
28    75
29    91
Name: math_score, dtype: int64

In [ ]:
print("---departments in this dataset---")
print(df['department'].unique())

---departments in this dataset---
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
print("----department wise counts-----")
print(df['department'].value_counts())

----department wise counts-----
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
df[df['department'] == 'Computer Science']

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
df[(df['department'] == 'Computer Science') & (df['attendance_percentage'] > 90)]

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
df['mean'] = (
    df['math_score']+
    df['science_score']+
    df['english_score']+
    df['programming_score']
)/4

df[(df['mean']>90) & (df['attendance_percentage']>90)]

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score,mean_score,mean
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023,371,92.75,92.75
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023,367,91.75,91.75
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023,365,91.25,91.25

In [ ]:
df['total_score'] = (
    df['math_score'] +
    df['science_score'] +
    df['english_score'] +
    df['programming_score']
)

df.groupby('department')['total_score'].agg(
    ['mean']
).sort_values(by = 'mean', ascending = False).reset_index()

         department        mean
0  Computer Science  340.153846
1       Electronics  277.500000
2        Mechanical  267.333333
3             Civil  235.800000